### ISSUE TITLE
failed with an exception.

### ISSUE THREAD

**Issue by dineshnaikb** [AgoraIO-Extensions/iris_method_channel_flutter#53]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':iris_method_channel:buildCMakeRelWithDebInfo[arm64-v8a]'.
> Build command failed.
  Error while executing process /home/XXXXXX/Android/Sdk/cmake/3.18.1/bin/ninja with arguments {-C /home/XXXXX/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0-rc.5/android/.cxx/RelWithDebInfo/6o504h5y/arm64-v8a iris_method_channel}
  ninja: Entering directory `/home/XXXXX/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0-rc.5/android/.cxx/RelWithDebInfo/6o504h5y/arm64-v8a'
  [1/4] Building C object CMakeFiles/iris_method_channel.dir/dart-sdk/include/dart_api_dl.c.o
  [2/4] Building CXX object CMakeFiles/iris_method_channel.dir/iris_life_cycle_observer.cc.o
  [3/4] Building CXX object CMakeFiles/iris_method_channel.dir/iris_event.cc.o
  FAILED: CMakeFiles/iris_method_channel.dir/iris_event.cc.o 

my operating system is <b>ubuntu</b>
@littleGnAl 
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by littleGnAl** [comment]
Can you share more error logs?

**Comment by dineshnaikb** [comment]
i am using in flutter using in Ubuntu

**Comment by littleGnAl** [comment]
We have tested it on the ubuntu 
https://github.com/AgoraIO-Extensions/iris_method_channel_flutter/blob/e92776b0427091f356667886731fe2e07463b87d/.github/workflows/ci.yaml#L126

I think a reproducible demo is helpful.

**Comment by littleGnAl** [comment]
duplicated https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1086
